version: "3"
networks:
  prestashop-1.7.8:
services:
  mysql:
    image: mysql:5.7
    container_name: prestashop-1.7.8-mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t_
    networks:
      - prestashop-1.7.8
  server:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop-1.7.8
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    environment:
      DB_SERVER: prestashop-1.7.8-mysql
    depends_on:
      - mysql
    networks:
      - prestashop-1.7.8
